name: ai_legal_advisor
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.2.1
  file_picker: ^8.0.0+1
  permission_handler: ^11.3.1
  http: ^1.1.0
  # Database and Backend
  supabase_flutter: ^2.6.0
  # Analytics and Crash Reporting
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  # SEO and Meta tags (for web)
  flutter_web_plugins:
    sdk: flutter
  web: any
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# إعدادات الأيقونة
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#1E3A8A"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#1E3A8A"
    theme_color: "#1E3A8A"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - .env
